### ISSUE TITLE
Put assets back to assets/components

### ISSUE THREAD

**Issue by Mark-H** [danyaPostfactum/modx-ace#1]
Noticed in the changelog that the files were moved to manager/components.... It cannot be assumed manager/components exists or is writable, and you really should've kept them in assets/components, as the Installer either creates it and makes sure it's writable, or it gives a warning to the user to create it.  

What made you change it to manager/components in the first place?

**Comment by gadgetto** [comment]
+1 to this

**Comment by bertoost** [comment]
+1000 to this
Please fix it as soon as possible!

**Comment by bertoost** [comment]
Did a fork and pull request
https://github.com/danyaPostfactum/modx-ace/pull/5

**Comment by ben-duffin** [comment]
um - could this explain the problem we are having! 

*\* Local Paths for ace ( which work ) show as **

``` javascript
<script type="text/javascript" src="/assets/components/ace/js/ace.js?v=222pl"></script>
<script type="text/javascript" src="/assets/components/ace/js/theme/chrome.js?v=222pl"></script>
<script type="text/javascript" src="/assets/components/ace/js/mode/php.js?v=222pl"></script>
<script type="text/javascript" src="/assets/components/ace/js/modx.codearea.js?v=222pl"></script>
```

*\* Live Paths for ace ( which DONT work ) show as **

``` javascript
<script type="text/javascript" src="/manager/components/ace/assets/ace/ace.js?v=222pl"></script>
<script type="text/javascript" src="/manager/components/ace/assets/ace/theme-chrome.js?v=222pl"></script>
<script type="text/javascript" src="/manager/components/ace/assets/ace/mode-php.js?v=222pl"></script>
<script type="text/javascript" src="/manager/components/ace/assets/modx.codearea.js?v=222pl"></script>
```

As I am new to ModX I am unsure of where I can fix this: its also very perplexing as the local server install works fine, but when we wrapped it as an archive and FTP'd to the live site ACE instantly stopped working.

**Comment by bertoost** [comment]
@ben-duffin see my commits
https://github.com/bertoost/modx-ace/commit/bfa81329a1e078b6ffb5e4586b499e8109a38dea
I have fixed this and send a pull request.. doesn't seem to be implemented yet unfortunately
https://github.com/danyaPostfactum/modx-ace/pull/5

**Comment by ben-duffin** [comment]
Aha! I'll keep a watch on this repo for the pull to come through ...

Thank you for getting back so promptly :)

**Comment by danyaPostfactum** [comment]
This is MODx issue:   http://tracker.modx.com/issues/8531

**Comment by bertoost** [comment]
I do not agree that with you!
The manager folder should not be touched by components
It's even described nowhere that it should function like that, so you cannot call that a bug

**Comment by danyaPostfactum** [comment]
> The manager folder should not be touched by components

Why do you think so?

> It's even described nowhere that it should function like that, so you cannot call that a bug

Manager is nothing more then another modx context.
Manager is a standalone context with the key `mgr`. It should not depends on its position. So, it is allowed to use different domain name for this (like dev.site.com for `dev` context, for example).  For proper work of manager panel, all javascripts, using AJAX must be placed in the same domain. This means that manager extras should place its scripts into manager folder.

**Comment by bertoost** [comment]
I got your point. But besides that; I think MODX should change this and this should not be a component what does things no other plugin will do at the moment. As long MODX doesn't describe this way of function I think you should not handle like this.

Besides that, as far I know Ace is the only one who do this, so maybe you can try to stick to the things as they are at the moment? Thanks!

**Comment by danyaPostfactum** [comment]
> As long MODX doesn't describe this way of function

See http://rtfm.modx.com/display/revolution20/Hardening+MODX+Revolution : 

> As with the manager, this (connectors) could also potentially live on a separate domain

You wrote:

> Besides that, as far I know Ace is the only one who do this,

CKeditor, AjaxManager and all my future extras :) And I hope another developers will realize this.

**Comment by bertoost** [comment]
As long you keep doing that and MODX will not support that (because of permissions and cross domain errors) people will continue to criticize your way of work. 

By the way;
The RTFM page in your post is showing how to move the folders, but not into another domain. So, what you're doing is not what they suggest. Within the same domain, in another subfolder, there will not be any problem.

**Comment by danyaPostfactum** [comment]
> The RTFM page in your post is showing how to move the folders, but not into another domain

Really? Please, read it again:

> As with the manager, this (connectors) could also potentially live on a separate domain

**Comment by jpdevries** [comment]
@danyaPostfactum this is a perfect example why extras shouldn't write to the manager, not all webservers are or should need to be configured to write there:
I'm working on a 2.2.8 site, don't have phpmyadmin or SSH currently just manager access. I installed Ace, webserver doesn't allow manager folder to be modified, and the result is the entire Manager crashed and is now rendered useless.
Any other thing to learn from this, MODX should fail for gracefully in these situations

**Comment by bertoost** [comment]
:+1: for that @jpdevries

**Comment by danyaPostfactum** [comment]
Done https://github.com/danyaPostfactum/modx-ace/commit/234a16dc47cc4622e1021233d97aadc5ad8046d3

**Comment by rtripault** [comment]
Probably a little late on the discussion, but i'm all with @danyaPostfactum on this one, and think manager assets belong to... manager folder!

MODX not "promoting" this feature is another story, but it clearly allows moving core, connectors & manager folders (in sub-folders/domains).
Furthermore, as stated in http://rtfm.modx.com/revolution/2.x/getting-started/installation/advanced-installation MODX (PHP process) should be able to "create the manager and connectors directories".

FWIW, most of my recent components (closed/open sources) follow this convention as well.
