### ISSUE TITLE
Tested with MODX Cloud

### ISSUE THREAD

**Issue by Robert-rx2-Ross** [danyaPostfactum/modx-ace#10]
Ace 1.3.1 works wonderfully on all of our hosts except MODX Cloud hosting where it appears to have no effect. No line numbers, syntax colouring, etc.

**Comment by jpdevries** [comment]
Did you test using Snapshots? Since Ace stores files in the /manager folder it requires being reinstalled after doing things like spinning up a new cloud from a Snapshot (or probably moving a MODX site in general)

**Comment by danyaPostfactum** [comment]
This should be fixed after moving assets back to writable /assets/ folder. Please let me know if you still have problems.
