### ISSUE TITLE
Fullscreen Mode MAC OSX

### ISSUE THREAD

**Issue by samtempledev** [danyaPostfactum/modx-ace#11]
Hi There,

I was wondering what or if there was a shortcut in the mac osx enviroment for the fullscreen mode just like windows Ctrl+F11?

Thanks

**Comment by danyaPostfactum** [comment]
It has such binding:

```
bindKey: {win: "Ctrl-F11", mac: "Command-Option-F11"}
```

But I did't test it, and even don't know what is Option key :)

I think it would be great to have a system setting for custom key bindings.

**Comment by samtempledev** [comment]
I think that using F11 is not a good key on a mac due to expose and audio controls, i have changed mine to Cmd-Option-Q and that works well for me, just a suggestion.

**Comment by danyaPostfactum** [comment]
Changed https://github.com/danyaPostfactum/modx-ace/commit/34ae08b23aa010e3464b5eac5543547988ca02c2
