### ISSUE TITLE
Requires Reinstallation

### ISSUE THREAD

**Issue by jpdevries** [danyaPostfactum/modx-ace#18]
Since Ace stores files in the Manager folder it requires being reinstalled after moving a MODX site (or spinning up a new MODX Cloud for a Snapshot)

**Comment by danyaPostfactum** [comment]
Did you ask MODx Cloud support about this issue?

**Comment by jpdevries** [comment]
It's reproducible outside of MODX cloud. Files should be stored in core/components
—
