### ISSUE TITLE
Resource Overview fatal error

### ISSUE THREAD

**Issue by Fi1osof** [danyaPostfactum/modx-ace#19]
Fatal error: Call to a member function get() on a non-object in /paas/c0701/www/core/cache/includes/elements/modplugin/1.include.cache.php on line 122

Error in this line: https://github.com/danyaPostfactum/modx-ace/blob/master/core/components/ace/elements/plugins/ace.plugin.php#L117

**Comment by danyaPostfactum** [comment]
Fixed https://github.com/danyaPostfactum/modx-ace/commit/2372eb7e8810fcaa224ae2432917f1fb676365a9

**Comment by Fi1osof** [comment]
if (!$modx->controller->resourceArray) { 

It`s not guaranted solution. $modx->controller->resourceArray may exists and not empty, but $modx->getObject('modContentType', $modx->controller->resourceArray['content_type']) still may return no result, and ->get() return fatal error.
Required
if($content_type = $modx->getObject('modContentType', $modx->controller->resourceArray['content_type'])){
    $mimeType = $content_type->get('mime_type'); 
}
