### ISSUE TITLE
Bug: Tabbing selected multiple lines of code creates duplicates of the selected code

### ISSUE THREAD

**Issue by benmarte** [danyaPostfactum/modx-ace#21]
I found a bug with 1.4.0 when you select multiple lines of code and press tab more than once it duplicates the selected code for each tab press.

Thanks again for integrating Emmet into this it is fantastic and the fullscreen option as well, keep up the great work.

**Comment by danyaPostfactum** [comment]
Fixed by updating Ace script (https://github.com/danyaPostfactum/modx-ace/commit/d96b6ab81af7cf9b034a1a965cb93b3418390a39 )
