### ISSUE TITLE
Command+Alt+q for Fullscreen key shortcut is not working on mac

### ISSUE THREAD

**Issue by lithiumlab** [danyaPostfactum/modx-ace#22]
This executes the QUIT mac command and closes all browser windows.

**Comment by danyaPostfactum** [comment]
What shortcut should be used? I'm Windows user..

**Comment by lithiumlab** [comment]
maybe something like Command+f11 if it is not mapped to anything already in the system or browsers. by the way. excellent plugin for devs. I'll investigate for a reliably better option than one that quits all windows and loses your current work :)

**Comment by lithiumlab** [comment]
Command+f12 can be a good choice because is often used  by some code editors.
Is not used system wide and is not used in Chrome.

**Comment by danyaPostfactum** [comment]
Thanks for your report. Fixed.
