### ISSUE TITLE
ACE lexicon gives some errors.

### ISSUE THREAD

**Issue by Viktorminator** [danyaPostfactum/modx-ace#24]
MODX Revolution 2.2.4-pl (traditional) core/components/ace/lexicon/ru/default.inc.php string 41 gives error - non existing variable. Commented this string to suppress errors.
++++++
MODX Revolution 2.2.4-pl (traditional) core/components/ace/lexicon/ru/default.inc.php строка 41 выдаёт ошибку - несуществующая переменная. Закомментил строку, чтобы не было ошибок.

**Comment by danyaPostfactum** [comment]
Спасибо, исправил.
