### ISSUE TITLE
scss code highlighting inside static chunks doesn't work

### ISSUE THREAD

**Issue by pepebe** [danyaPostfactum/modx-ace#25]
I have a a couple of static chunks containing scss code. Even though scss files edited over the file tree are properly hightlighted, inside a chunk they present themselves in boring black and white. 

Is there any chance we can add scss code highlighting inside static chunk views?

If its not possible to automatically guess the file type, we could get the information from the static file path.

Regards,

pepebe

**Comment by danyaPostfactum** [comment]
I did not test it much. Please let me know if you find a bug.
