### ISSUE TITLE
Проблема с Ace

### ISSUE THREAD

**Issue by Tramp1357** [danyaPostfactum/modx-ace#26]
Добрый день.
У меня стоит MODX revo 2.2.9, Ace, AjaxManager.
В настройках я убрал расширение '.html' у документов.
При редактировании ресурса в modxsdk ace нормально включается, подсвечивает синтаксис и т.п., но при редактировании документа штатными средствами MODX открывается голый редактор (без ace). Обновление страницы не помогает. 

P.S.: Пробовал добавить в плагин на событие OnFileEditFormPrerender пустое расширение — не помогло, а ".html" ставить очень не хочется

**Comment by danyaPostfactum** [comment]
Настройки чпу никаким образом не влияют на редактор. Или речь про редактирование файлов?
В консоли браузера ошибки имеются? Редактирование других объектов, например чанков, работает нормально?

**Comment by Tramp1357** [comment]
Нет, не файлы. В консоли ошибок нет. И это происходит только при редактировании ресурсов. на чанках, сниппетах и плагинах все работает.

**Comment by danyaPostfactum** [comment]
А до изменения настроек чпу редактирование работало?
Установите системную настройку use_editor в false

**Comment by Tramp1357** [comment]
Установил use_editor в false, все заработало.

**Comment by Tramp1357** [comment]
у меня установлен только Ace

**Comment by Tramp1357** [comment]
т.е. мне в будущем так же поступать?

**Comment by danyaPostfactum** [comment]
Да, это так задумано. Либо use_editor в false либо снять галочку "использовать RTE" на ресурсе.
То есть ace будет появляться тогда, когда отключен визуальный редактор.

**Comment by Tramp1357** [comment]
ясно. спасибо.
