### ISSUE TITLE
Ace and Revo 2.3

### ISSUE THREAD

**Issue by ghost** [danyaPostfactum/modx-ace#29]
Ace works fine on Revo 2.3 (so far) but has to be downloaded and installed locally.

**Comment by adamwintle** [comment]
I just noticed it was missing from the Package Management (or is it Apps Management now), any idea why Ace is missing?

**Comment by danyaPostfactum** [comment]
New version 1.4.3-pl is marked as modx edge version compatible. Now it should be available from Apps Management. Please let me know if you have issues with ace in Revo 2.3.
