### ISSUE TITLE
Two lexicon files (default.inc.php + properties.inc.php) or one (default.inc.php)?

### ISSUE THREAD

**Issue by gadgetto** [danyaPostfactum/modx-ace#3]
As I just finished translating the lexicon file of the current version to German language, I discovered that the current download version seems to have two lexicon files included (default.inc.php + properties.inc.php).

The latest version on GitHub only has one lexicon file (default.inc.php).

Which is the correct version?
(for now I have only translated the default.inc.php and it works)

**Comment by danyaPostfactum** [comment]
Current download version has default.inc.php only.
properties.inc.php file is obsolete and has no usage for now.

Thanks for the translation.

**Comment by gadgetto** [comment]
OK - thanks
