### ISSUE TITLE
Unknown errors with Ace 1.4.3

### ISSUE THREAD

**Issue by lithiumlab** [danyaPostfactum/modx-ace#32]
Recently installed new Ace update and started getting this error warnings.
I don't see the problem. Any suggestions?

![screen shot 2014-03-16 at 10 27 59 am](https://f.cloud.github.com/assets/494499/2431059/e2e09098-ad17-11e3-9fcf-6a8d51620df3.png)

Tried uninstalling the latest update and then Ace previous Addon wasn't activated in Chunk / Snippet windows.

**Comment by danyaPostfactum** [comment]
Did you get this fixed? Try Ctrl+F5. Try to remove all previous versions and reinstall latest one.

It Looks like modx.texteditor.js file was not replaced on your server.

**Comment by lithiumlab** [comment]
It did fixed the problem uninstalling all previous packages.
Also cleared the site cache and flushed sessions just in case.
Thanks.

By the way. I just can't work without this Extra. Kudos! It really improves my workflow.
Would love to see some Reindent option / command.
