### ISSUE TITLE
Latest update (1.3.0-rc3) not recognized by MODx package manager

### ISSUE THREAD

**Issue by gadgetto** [danyaPostfactum/modx-ace#8]
Strange but for me the latest update doesn't show up in MODx package manager. Still at version 1.2.1-rc2.
I already had this problem with another other component. Tested this in 3 MODx installations on 2 different servers.
Is it only me?

**Comment by danyaPostfactum** [comment]
> Is it only me?

No, this is known problem. http://tracker.modx.com/issues/9122

**Comment by danyaPostfactum** [comment]
Closing, since this is a not extension-specific issue and seems to be "By Design".
